client_token = "test_token"
AWS_ACCESS_KEY = "test_aws_access_key"
#AWS_SECRET_ACCESS_KEY = ""
password = "test_passwd"
config_name = "harbor/admin"
config_root = "secret"
target_account = "test01"
vlt_addr = "http://192.168.64.101:8200"